stages:
  - build
  - push
  - deploy

cache:
  paths:
    - .cache/pip

build:
  stage: build
  only:
    - master
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo BUYING_MONGO_HOST=$BUYING_MONGO_HOST >> .env
    - echo BUYING_MONGO_PORT=$BUYING_MONGO_PORT >> .env
    - echo BUYING_MONGO_USER=$BUYING_MONGO_USER >> .env
    - echo BUYING_MONGO_PASS=$BUYING_MONGO_PASS >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS 
    - docker build -t buy:0.0.1 .

dev_deploy:
  stage: deploy
  only:
    - master
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo BUYING_MONGO_HOST=$BUYING_MONGO_HOST >> .env
    - echo BUYING_MONGO_PORT=$BUYING_MONGO_PORT >> .env
    - echo BUYING_MONGO_USER=$BUYING_MONGO_USER >> .env
    - echo BUYING_MONGO_PASS=$BUYING_MONGO_PASS >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build

push:
  stage: push
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo BUYING_MONGO_HOST="172.16.16.16" >> .env
    - echo BUYING_MONGO_PORT=$BUYING_MONGO_PORT >> .env
    - echo BUYING_MONGO_USER=$BUYING_MONGO_USER >> .env
    - echo BUYING_MONGO_PASS=$BUYING_MONGO_PASS >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker build -t buying:0.0.1 . #-t nexus.aasood.com/backend/buying:$CI_COMMIT_SHORT_SHA
#    - docker push nexus.aasood.com/backend/buying:$CI_COMMIT_SHORT_SHA

master_deploy:
  stage: deploy
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo BUYING_MONGO_HOST="172.16.16.16" >> .env
    - echo BUYING_MONGO_PORT=$BUYING_MONGO_PORT >> .env
    - echo BUYING_MONGO_USER=$BUYING_MONGO_USER >> .env
    - echo BUYING_MONGO_PASS=$BUYING_MONGO_PASS >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build
