version: "3"

services:
    mongodb:
        image: mongo:4.4.4
        container_name: mongo-db-coupon
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        volumes:
            - mongodb-data-coupon:/data/db-coupon
        ports:
            - ${COUPON_MONGO_PORT}:27017
        restart: unless-stopped
    mongo-express:
        image: mongo-express:latest
        container_name: mongo_ex_buy
        environment:
            - ME_CONFIG_MONGODB_SERVER=172.16.16.7
            - ME_CONFIG_MONGODB_PORT=${COUPON_MONGO_PORT}
            - ME_CONFIG_MONGODB_ADMINUSERNAME=
            - ME_CONFIG_MONGODB_ADMINPASSWORD=
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=qweQWE
        ports:
            - "8893:8081"
        restart: always

    api:
        build: .
        environment:
          - TZ=Asia/Tehran

volumes:
    mongodb-data-buy:

